### ISSUE TITLE
개발 해야할 일 ~ 5월 8일

### ISSUE THREAD

**Issue by Yeogiwon** [GAMPOT-DEV/Project_Blind#1]
1. 협업 프로세스 구성(변수 명칭 및 코드 작성법 통일 등 github활용 포함)
2. 플레이어 이동 및 대쉬(방향키 + 스페이스바 조합)
3. 적 유닛(AI) 만들기(레이캐스트든 콜라이더든 생각해보기)
4. 카메라 이동 관해서 생각해보기(메트로바니아류 게임 해보거나 플레이영상 보기)(5월 8일까지는 구현 완료)
5. 파동(오브젝트 충돌 시 반사 + 윤곽 들어나기)에 대해 고민해보기

**Comment by dongcheolpark** [comment]
1번 완료

**Comment by dongcheolpark** [comment]
2번 완료

**Comment by dongcheolpark** [comment]
4번 완료
