### ISSUE TITLE
Wave Sense에 적 유닛의 산하에 있는 모든 콜라이더가 반응함

### ISSUE THREAD

**Issue by kjhcocomi** [GAMPOT-DEV/Project_Blind#112]
![image](https://user-images.githubusercontent.com/85743027/182329708-47df368a-b19a-4cd5-a08a-fe1490ea224d.png)

원래는 WaveHitObj를 가지고 있는 오브젝트의 콜라이더 에서만 반응하도록 설계한 것 같은데
사진처럼 적 유닛의 산하에 있는 4개의 콜라이더가  지금 WaveHitObj의 OnTriggerEnter2D에서  전부 반응합니다.

![image](https://user-images.githubusercontent.com/85743027/182330538-0bf306aa-02ab-4e80-8e38-93a99152e76c.png)

4개의 콜라이더 모두 하나의 RIgidBody2D랑 연결되어있어서 발생하는 것 같습니다.
OnTriggerEnter2D를 WaveSense에서 호출하는식으로 바꾸는건 어떨까요?

**Comment by dongcheolpark** [comment]
trigger는 wavesense에서 호출하고 있는데 콜라이더들이 전부 유닛 아래에 있어서 발생하는 현상인것 같습니다.

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: 김종현 ***@***.***>
보낸 날짜: Tuesday, August 2, 2022 5:42:37 PM
받는 사람: GAMPOT-DEV/Project_Blind ***@***.***>
참조: Subscribed ***@***.***>
제목: [GAMPOT-DEV/Project_Blind] Wave Sense에 적 유닛의 산하에 있는 모든 콜라이더가 반응함 (Issue #112)


[image]<https://user-images.githubusercontent.com/85743027/182329708-47df368a-b19a-4cd5-a08a-fe1490ea224d.png>

원래는 WaveHitObj를 가지고 있는 오브젝트의 콜라이더 에서만 반응하도록 설계한 것 같은데
사진처럼 적 유닛의 산하에 있는 4개의 콜라이더가 지금 WaveHitObj의 OnTriggerEnter2D에서 전부 반응합니다.

[image]<https://user-images.githubusercontent.com/85743027/182330538-0bf306aa-02ab-4e80-8e38-93a99152e76c.png>

4개의 콜라이더 모두 하나의 RIgidBody2D랑 연결되어있어서 발생하는 것 같습니다.
OnTriggerEnter2D를 WaveSense에서 호출하는식으로 바꾸는건 어떨까요?

**Comment by kjhcocomi** [comment]
trigger 지금 WaveHitObj에서 호출하고 있는거 아닌가요??

**Comment by dongcheolpark** [comment]
아 업데이트가 안되어있었네요 잠시만요

**Comment by kjhcocomi** [comment]
아하 그럼 해결 된거죠?

**Comment by dongcheolpark** [comment]
머지하고 한번 확인해보실래요?

**Comment by kjhcocomi** [comment]
된거같네요 이슈 닫을게용
