### ISSUE TITLE
죽은 다음에 설정 들어갔다가 메인으로 나가기 누르면 게임 먹통됨

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/Project_Blind#219]

**Comment by kjhcocomi** [comment]
![image](https://user-images.githubusercontent.com/85743027/191939553-61625287-e7e9-4907-928c-f100edace5b2.png)
전 버튼 누르면 ui 클리어해주고 메인 씬으로 나가게 하는 코드만 써놔서 원인을 잘 모르겠네요..
