### ISSUE TITLE
전장의 안개 연구

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/Project_Blind#54]
어려운 내용이 될 것 같아서 다같이 고민해 보면 좋을 것 같습니다.
전장의 안개 사양은 다음과 같습니다.

 - 가시 범위 안은 모든 오브젝트들이 보여야 함
 - 가시 범위 밖은 크게 두 가지 영역으로 나뉨
     1. 한 번도 가지 않아 아무것도 보이지 않는 영역
     2. 한 번 이상 방문해 흐릿하게 배경이 보이는 영역
 - 현재 2D Light로 가시 범위를 제한 하는데 이를 이용하면 그림자를 구현하는 것이 편리하지만 전장의 안개 시스템과 합치기 힘듦
 - 맵을 이동해도 정보는 남아 있어야 함. 아마 게임을 꺼도 정보는 계속 남아 있어야 할 것으로 예상

**Comment by kjhcocomi** [comment]
참고한 곳:
https://www.youtube.com/watch?v=vUYZiQ3C4hU
https://github.com/Keyiter/One-Minute-Unity/tree/%238-Fog-of-War

**Comment by dongcheolpark** [comment]
```c#
    public void MakeHole(Vector2 position, float holeRadius)
    {
        Vector2Int pixelPosition = WorldToPixel(position);
        int radius = Mathf.RoundToInt(holeRadius * pixelScale.x / worldScale.x);
        int px, nx, py, ny, distance;
        for (int i = 0; i < radius; i++)
        {
            distance = Mathf.RoundToInt(Mathf.Sqrt(radius * radius - i * i));
            for (int j = 0; j < distance; j++)
            {
                px = Mathf.Clamp(pixelPosition.x + i, 0, pixelScale.x);
                nx = Mathf.Clamp(pixelPosition.x - i, 0, pixelScale.x);
                py = Mathf.Clamp(pixelPosition.y + j, 0, pixelScale.y);
                ny = Mathf.Clamp(pixelPosition.y - j, 0, pixelScale.y);

                fogOfWarTexture.SetPixel(px, py, Color.black);
                fogOfWarTexture.SetPixel(nx, py, Color.black);
                fogOfWarTexture.SetPixel(px, ny, Color.black);
                fogOfWarTexture.SetPixel(nx, ny, Color.black);
            }
        }
        fogOfWarTexture.Apply();
        CreateSprite();
    }
```
이 코드를 그래픽카드로 넘길 필요가 있습니다.
컴퓨트 셰이더를 이용하면 처리할 수 있을 듯 합니다.
https://rito15.github.io/posts/unity-compute-shader/
관련 사이트 남깁니다

**Comment by dongcheolpark** [comment]
https://rito15.github.io/posts/fog-of-war/
좋은 글인 것 같아서 가져와 봤습니다.
우리가 구현하려는 목표와 가장 흡사해 보입니다

**Comment by dongcheolpark** [comment]
#67

**Comment by dongcheolpark** [comment]
> https://rito15.github.io/posts/fog-of-war/ 좋은 글인 것 같아서 가져와 봤습니다. 우리가 구현하려는 목표와 가장 흡사해 보입니다

작업중

**Comment by dongcheolpark** [comment]
https://nicotina04.tistory.com/197?category=992306
새로운 방식으로 구현 작업중

**Comment by nicotina04** [comment]
안녕하세요. 블로그 로그를 보고 찾아와서 남깁니다.

현재 게임 개발과 관련한 시간을 내기 어려워 글을 더 쓰지 못한 게 있는데요. 해당 자료에 덧붙여서

https://github.com/LeLocTai/Fog-of-war

이 저장소의 소스코드를 참고했습니다. 전장의 안개를 구현할 때 참고하시면 좋을 것 같습니다.

감사합니다.

**Comment by dongcheolpark** [comment]
> 안녕하세요. 블로그 로그를 보고 찾아와서 남깁니다.
> 
> 현재 게임 개발과 관련한 시간을 내기 어려워 글을 더 쓰지 못한 게 있는데요. 해당 자료에 덧붙여서
> 
> https://github.com/LeLocTai/Fog-of-war
> 
> 이 저장소의 소스코드를 참고했습니다. 전장의 안개를 구현할 때 참고하시면 좋을 것 같습니다.
> 
> 감사합니다.

찾아와 주셔서 감사합니다!!
블로그 글은 잘 읽어 보았고 구현 까지는 성공했으나 현재 게임에 쓰이고 있는 URP2D 파이프 라인과는 상충하는 부분이 많아 Light2D를 이용해 FieldOfView를 구현하고 적 유닛이 Shadow안에 들어갈 경우 셰이더를 통해 보이지 않게 하는 방식으로 구현하였습니다.
전장의 안개는 개발 기간안에 맞추기 힘들 것 같아서 FOV만 구현하기로 합의 된 상태입니다. 
도움 주셔서 감사합니다!!
