### ISSUE TITLE
씬 체인지 과정에서 dont destroy on load부분에 문제가 있습니다.

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/Project_Blind#63]
씬 체인지 과정에서 dont destroy on load부분에 문제가 있습니다.
GameManager를 수정해야 할 것 같습니다

_Originally posted by @hhtboy in https://github.com/GAMPOT-DEV/Project_Blind/issues/31#issuecomment-1140381310_

**Comment by kjhcocomi** [comment]
각 씬에서만 유효한 GameManager 역할을 하는 클래스를 만드는건 어떨까요?
(김종현 씬에서 KjhTestScene이 그런 역할)

**Comment by dongcheolpark** [comment]
> 각 씬에서만 유효한 GameManager 역할을 하는 클래스를 만드는건 어떨까요? (김종현 씬에서 KjhTestScene이 그런 역할)

이름은 어떤 걸로 하면 좋을까요? [SceneName]GameManager이런식으로 통일하는게 좋을까요?

**Comment by kjhcocomi** [comment]
그런식으로 씬의 이름이 들어가면 좋을 듯 합니당

**Comment by hhtboy** [comment]
Gamemanager의 FixedUpdate 부분에 player의 null체크를 해서 임시로 해결했습니다.
